name: translator_plus
description: A free and unlimited Google Translate API for Dart. You can use it for translate strings and text for educational purpose.
version: 1.0.0
repository: https://github.com/HusamAwad2001/translator_plus

environment:
  sdk: ^3.0.2

# Add regular dependencies here.
dependencies:
  http: ^1.1.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
